import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'es' | 'fr' | 'de' | 'hi' | 'zh' | 'ja' | 'pt' | 'te';

const translations: Record<Language, Record<string, string>> = {
  en: {
    dashboard: 'Dashboard',
    courses: 'Courses',
    quizzes: 'Quizzes',
    analytics: 'Analytics',
    jobs: 'Jobs',
    profile: 'Profile',
    students: 'Students',
    children: 'Children',
    performance: 'Performance',
    alerts: 'Alerts',
    settings: 'Settings',
    logout: 'Logout',
    notifications: 'Notifications',
    languages: 'Languages',
    theme: 'Theme',
    account: 'Account',
    profile_info: 'Profile Information',
    dark_mode: 'Dark Mode',
    light_mode: 'Bright Mode',
    edit_profile: 'Edit Profile',
    language: 'Language',
    save_changes: 'Save Changes',
    about_app: 'About App',
    version: 'Version',
    build: 'Build',
    platform: 'Platform',
  },
  es: {
    dashboard: 'Panel de Control',
    courses: 'Cursos',
    quizzes: 'Cuestionarios',
    analytics: 'Análisis',
    jobs: 'Trabajos',
    profile: 'Perfil',
    students: 'Estudiantes',
    children: 'Hijos',
    performance: 'Desempeño',
    alerts: 'Alertas',
    settings: 'Configuración',
    logout: 'Cerrar Sesión',
    notifications: 'Notificaciones',
    languages: 'Idiomas',
    theme: 'Tema',
    account: 'Cuenta',
    profile_info: 'Información del Perfil',
    dark_mode: 'Modo Oscuro',
    light_mode: 'Modo Claro',
    edit_profile: 'Editar Perfil',
    language: 'Idioma',
    save_changes: 'Guardar Cambios',
    about_app: 'Acerca de la Aplicación',
    version: 'Versión',
    build: 'Compilación',
    platform: 'Plataforma',
  },
  fr: {
    dashboard: 'Tableau de Bord',
    courses: 'Cours',
    quizzes: 'Quizz',
    analytics: 'Analytique',
    jobs: 'Emplois',
    profile: 'Profil',
    students: 'Étudiants',
    children: 'Enfants',
    performance: 'Performance',
    alerts: 'Alertes',
    settings: 'Paramètres',
    logout: 'Déconnexion',
    notifications: 'Notifications',
    languages: 'Langues',
    theme: 'Thème',
    account: 'Compte',
    profile_info: 'Informations du Profil',
    dark_mode: 'Mode Sombre',
    light_mode: 'Mode Clair',
    edit_profile: 'Modifier le Profil',
    language: 'Langue',
    save_changes: 'Enregistrer les Modifications',
    about_app: 'À Propos de l\'Application',
    version: 'Version',
    build: 'Build',
    platform: 'Plateforme',
  },
  de: {
    dashboard: 'Dashboard',
    courses: 'Kurse',
    quizzes: 'Quize',
    analytics: 'Analytik',
    jobs: 'Stellen',
    profile: 'Profil',
    students: 'Schüler',
    children: 'Kinder',
    performance: 'Leistung',
    alerts: 'Benachrichtigungen',
    settings: 'Einstellungen',
    logout: 'Abmelden',
    notifications: 'Benachrichtigungen',
    languages: 'Sprachen',
    theme: 'Design',
    account: 'Konto',
    profile_info: 'Profilinformationen',
    dark_mode: 'Dunkler Modus',
    light_mode: 'Heller Modus',
    edit_profile: 'Profil Bearbeiten',
    language: 'Sprache',
    save_changes: 'Änderungen Speichern',
    about_app: 'Über die App',
    version: 'Version',
    build: 'Build',
    platform: 'Plattform',
  },
  hi: {
    dashboard: 'डैशबोर्ड',
    courses: 'पाठ्यक्रम',
    quizzes: 'प्रश्नोत्तरी',
    analytics: 'विश्लेषण',
    jobs: 'नौकरियां',
    profile: 'प्रोफ़ाइल',
    students: 'छात्र',
    children: 'बच्चे',
    performance: 'प्रदर्शन',
    alerts: 'सतर्कताएं',
    settings: 'सेटिंग',
    logout: 'लॉग आउट',
    notifications: 'सूचनाएं',
    languages: 'भाषाएं',
    theme: 'थीम',
    account: 'खाता',
    profile_info: 'प्रोफ़ाइल जानकारी',
    dark_mode: 'गहरा मोड',
    light_mode: 'हल्का मोड',
    edit_profile: 'प्रोफ़ाइल संपादित करें',
    language: 'भाषा',
    save_changes: 'परिवर्तन सहेजें',
    about_app: 'ऐप के बारे में',
    version: 'संस्करण',
    build: 'निर्माण',
    platform: 'मंच',
  },
  zh: {
    dashboard: '仪表板',
    courses: '课程',
    quizzes: '测验',
    analytics: '分析',
    jobs: '工作',
    profile: '个人资料',
    students: '学生',
    children: '孩子们',
    performance: '表现',
    alerts: '警报',
    settings: '设置',
    logout: '登出',
    notifications: '通知',
    languages: '语言',
    theme: '主题',
    account: '账户',
    profile_info: '个人资料信息',
    dark_mode: '深色模式',
    light_mode: '浅色模式',
    edit_profile: '编辑个人资料',
    language: '语言',
    save_changes: '保存更改',
    about_app: '关于应用',
    version: '版本',
    build: '构建',
    platform: '平台',
  },
  ja: {
    dashboard: 'ダッシュボード',
    courses: 'コース',
    quizzes: 'クイズ',
    analytics: 'アナリティクス',
    jobs: 'ジョブ',
    profile: 'プロフィール',
    students: '学生',
    children: '子供',
    performance: 'パフォーマンス',
    alerts: 'アラート',
    settings: '設定',
    logout: 'ログアウト',
    notifications: '通知',
    languages: '言語',
    theme: 'テーマ',
    account: 'アカウント',
    profile_info: 'プロフィール情報',
    dark_mode: 'ダークモード',
    light_mode: 'ライトモード',
    edit_profile: 'プロフィールを編集',
    language: '言語',
    save_changes: '変更を保存',
    about_app: 'このアプリについて',
    version: 'バージョン',
    build: 'ビルド',
    platform: 'プラットフォーム',
  },
  pt: {
    dashboard: 'Painel de Controle',
    courses: 'Cursos',
    quizzes: 'Questionários',
    analytics: 'Análise',
    jobs: 'Empregos',
    profile: 'Perfil',
    students: 'Alunos',
    children: 'Filhos',
    performance: 'Desempenho',
    alerts: 'Alertas',
    settings: 'Configurações',
    logout: 'Sair',
    notifications: 'Notificações',
    languages: 'Idiomas',
    theme: 'Tema',
    account: 'Conta',
    profile_info: 'Informações do Perfil',
    dark_mode: 'Modo Escuro',
    light_mode: 'Modo Claro',
    edit_profile: 'Editar Perfil',
    language: 'Idioma',
    save_changes: 'Salvar Alterações',
    about_app: 'Sobre o Aplicativo',
    version: 'Versão',
    build: 'Compilação',
    platform: 'Plataforma',
  },
  te: {
    dashboard: 'డాష్‌బోర్డ్',
    courses: 'కోర్సులు',
    quizzes: 'క్విజ్‌లు',
    analytics: 'విశ్లేషణ',
    jobs: 'ఉద్యోగాలు',
    profile: 'ప్రొఫైల్',
    students: 'విద్యార్థులు',
    children: 'పిల్లలు',
    performance: 'పనితీరు',
    alerts: 'అలర్టులు',
    settings: 'సెట్టింగ్‌లు',
    logout: 'లాగౌట్',
    notifications: 'నోటిఫికేషన్‌లు',
    languages: 'భాషలు',
    theme: 'థీమ్',
    account: 'ఖాతా',
    profile_info: 'ప్రొఫైల్ సమాచారం',
    dark_mode: 'నల్ల మోడ్',
    light_mode: 'లైట్ మోడ్',
    edit_profile: 'ప్రొఫైల్‌ను సవరించు',
    language: 'భాష',
    save_changes: 'మార్పులను సేవ్ చేయండి',
    about_app: 'అప్‌కు గురించి',
    version: 'సంస్కరణ',
    build: 'నిర్మాణం',
    platform: 'ప్ల్యాట్‌ఫర్మ్',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  // Load saved language on mount
  useEffect(() => {
    const saved = localStorage.getItem('preferredLanguage') as Language | null;
    if (saved && translations[saved]) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('preferredLanguage', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
